#ifndef SMART_ENV_MONITOR_CONFIG_H
#define SMART_ENV_MONITOR_CONFIG_H

#define MONITOR_SAMPLE_PERIOD_MS      1000U
#define MONITOR_UART_BAUDRATE         115200U

#define MONITOR_TEMP_HIGH_C           35.0F
#define MONITOR_HUMIDITY_HIGH_PCT     80.0F
#define MONITOR_LIGHT_LOW_LUX         50.0F

#define MONITOR_JSON_BUFFER_SIZE      192U

#endif
